spring:
  application:
    name: bookshop-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: bookshop_product
              uri: lb://product-service
              predicates:
                - Path=/product/**
            - id: bookshop_authentication
              uri: lb://authentication-service
              predicates:
                - Path=/auth/**

server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
