spring:
  application:
    name: authentication-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore
    username: root
    password: admin123

jwt:
  secret: LaCbqQ1+a6+kFq3xdV1s4teNL/+Bricr9mvrYgZR+ew=
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
